author: boypt # 作者
description: boypt's blog
keyword: hexo, boypt

excerpt_link: Read more

menu:
 Home: /
 Series: /series/
 Tags: /tags/
 Archives: /archives/
 Projects: "https://github.com/boypt"
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set utterances, gitment, uyan or disqus
comment: 

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics: 
# disqus config
disqus_shortname: 

about: 
  banner: ""
  avatar: /images/avatar.jpg
  description: ""
  github_username: boypt
  weibo_username: ""
  twitter_username: boypt
  linkedin_username: ''
  zhihu_username: ''
  douban_username: ''
  
# MathJax Support
mathjax:
  enable: false
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
  enable: true

